name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.13.1, 12.19.0]
        mongodb-version: [3.6.19]
        redis-version: [4.0.14]

    steps:
    - name: Setup Node ${{ matrix.node-version }} 
      uses: actions/setup-node@v1
      with:
        node-version:  ${{ matrix.node-version }}

    - name: Checkout from Git
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install ESLint
      run: npm install -g eslint

    # - name: poison pill
    #   run: |-
    #     set -x
    #     echo ${{ matrix.node-version }} |grep 14.13.0

    - name: Run ESLint
      run: eslint .

    - name: Run npm install
      run: npm install

    - name: Run tests and coverage report
      run: npm run coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}

  notify_slack:
    if: always()
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Notify Slack
      uses: homoluctus/slatify@master
      with:
        type: ${{ needs.test.result }}
        job_name: '${{ github.repository }} - Tests'
        channel: '#development'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
        icon_emoji: ':mediocrebot:'
        username: 'mediocrebot'
