name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        mongodb-version: [4.0.23]
        node-version: [12.9.0, 14.15.1]
        redis-version: [4.0.14]
    
    env:
      DO_COVERALLS: 14.15.1/4.0.23/4.0.14

    steps:
    - name: Setup Node ${{ matrix.node-version }} 
      uses: actions/setup-node@v1
      with:
        node-version:  ${{ matrix.node-version }}

    - name: Checkout from Git
      uses: actions/checkout@v2
      with:
        persist-credentials: false


    - name: Install ESLint
      run: npm install -g eslint

    - name: Run ESLint
      run: eslint .

    - name: Run npm install
      run: npm install

    - name: Run tests and coverage report
      run: |-
        if [ "${{ matrix.node-version }}/${{ matrix.mongodb-version }}/${{ matrix.redis-version }}"x == "${DO_COVERALLS}"x ]
        then
          npm run coveralls
        else
          true
        fi
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}

    - name: Run tests and coverage report
      run: |-
        if [ ! "${{ matrix.node-version }}/${{ matrix.mongodb-version }}/${{ matrix.redis-version }}"x == "${DO_COVERALLS}"x ]
        then
          npm test
        else
          true
        fi
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}

  notify_slack:
    if: always()
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Notify Slack
      uses: homoluctus/slatify@master
      with:
        type: ${{ needs.test.result }}
        job_name: '${{ github.repository }} - Tests'
        channel: '#pitney-bowes'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
        icon_emoji: ':mediocrebot:'
        username: 'mediocrebot'
