name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - name: Setup Node 14.11.0
      uses: actions/setup-node@v1
      with:
        node-version: [12.18.4, 14.13.0]

    - name: Checkout from Git
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install ESLint
      run: npm install -g eslint

    - name: Run ESLint
      run: eslint .

    - name: Run npm install
      run: npm install

    - name: Run tests and coverage report
      run: npm run coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}

    - name: Notify Slack
      if: always()
      uses: homoluctus/slatify@master
      with:
        type: ${{ job.status }}
        job_name: '${{ github.repository }} - Tests '
        channel: '#development'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
        icon_emoji: ':mediocrebot:'
        username: 'mediocrebot'
